### PR TITLE
Improve layout of apps list

### PR DESCRIPTION
**Pull request by Domi04151309**
Fixes alignment issues of the current list and uses a standard android app bar instead of the custom back button.

### CODE REVIEW

**Comment by patri9ck** [comment]
I think it looks great but the color are a bit wrong in the apps activity (e.g. the background or the top bar). All colors currently used by the app are defined in /[app](https://github.com/patri9ck/a2ln-app/tree/main/app)/[src](https://github.com/patri9ck/a2ln-app/tree/main/app/src)/[main](https://github.com/patri9ck/a2ln-app/tree/main/app/src/main)/[res](https://github.com/patri9ck/a2ln-app/tree/main/app/src/main/res)/values/ and [a2ln-app](https://github.com/patri9ck/a2ln-app)/[app](https://github.com/patri9ck/a2ln-app/tree/main/app)/[src](https://github.com/patri9ck/a2ln-app/tree/main/app/src)/[main](https://github.com/patri9ck/a2ln-app/tree/main/app/src/main)/[res](https://github.com/patri9ck/a2ln-app/tree/main/app/src/main/res)/[values-night](https://github.com/patri9ck/a2ln-app/tree/main/app/src/main/res/values-night)/colors.xml.

**Comment by Domi04151309** [comment]
It should use the correct colors now

**Comment by patri9ck** [comment]
Looks great! Three more things I notice:
Screenshot

- The purple color when you are at the top of the list and try to scroll further up
- The text color on the top bar
- The checkbox color (doesn't look bad but maybe we could use its color at more positions in the app or just give it also a color from colors.xml)

**Comment by Domi04151309** [comment]
What exactly do you mean by the text color of the top bar?
The other two colors can be done using the theme. I suggest doing them in another PR.

**Comment by patri9ck** [comment]
Sorry for this taking so long, had a busy week...
Screenshot
This is what I mean. When compared to other text colors in the app, you can see that it doesn't use `@color/text`.

Before merging this, I would at least like to change/remove that purple color. Do you know what I have to look for? Unfortunately, I don't know what it's called. The checkbox color is fine for now.

**Comment by Domi04151309** [comment]
The greenish color is the `colorAccent` and the purple one the `colorPrimary` (see the last commit).
To change the app bar's color is more difficult than just changing one value. I highly suggest reading about [text colors](https://material.io/design/color/text-legibility.html) and the general [design components](https://material.io/components?platform=android).

**Comment by patri9ck** [comment]
Thank you very much! It looks great.

I found a way to change the text color in the action bar by setting `android:textColorPrimary` to `@color/text` though it only works in light mode. If we cannot find a solution for this, I will merge it.

**Comment by patri9ck** [comment]
Merging this as I cannot find a solution and I don't want to hold back these changes because of that small thing.

I will create a new release that includes these changes.

**Pull request merged**
