### PR TITLE
Material 3 adoption

### PR DESCRIPTION
**Pull request by cyb3rko**
It's me again.  
Be sure to test it out and if you like it / find any issues.

### CODE REVIEW

**Comment by cyb3rko** [comment]
@patri9ck Any updates so far? :)

**Comment by patri9ck** [comment]
Really like the new theme! Can we somehow make the accent color adopt to Material You?

**Comment by patri9ck** [comment]
I don't really think it's necessary. I didn't see any Google apps have it. But if you want to, you can also add it. Maybe then as a switch between light/dark/system/Material You?

**Comment by cyb3rko** [comment]
It's added without a preference switch for now.  
Furthermore I let the UI draw over the system bars to fix their colors.

Please check if everything is as you like it.

**Pull request merged**
